### ISSUE TITLE
Crash on linux

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#237]
@hbenl is running into a crash at/near startup with the linux release.  Here is the backtrace output from gdb:

```
(gdb) cont
Continuing.
[New Thread 0x7efd9dc7b640 (LWP 31757)]
[New Thread 0x7efd8b2d8640 (LWP 31758)]
[Thread 0x7efd8b2d8640 (LWP 31758) exited]
[New Thread 0x7efd8aad7640 (LWP 31759)]
[New Thread 0x7efd8b2d8640 (LWP 31760)]
[New Thread 0x7efd8a4f6640 (LWP 31761)]
[New Thread 0x7efd89c58640 (LWP 31762)]
[New Thread 0x7efd851ff640 (LWP 31763)]
[New Thread 0x7efd851be640 (LWP 31764)]
[New Thread 0x7efd8517d640 (LWP 31765)]
[New Thread 0x7efd85174640 (LWP 31766)]
[New Thread 0x7efd84f75640 (LWP 31767)]
[New Thread 0x7efd84d76640 (LWP 31768)]
[New Thread 0x7efd84b77640 (LWP 31769)]
[New Thread 0x7efd84978640 (LWP 31770)]
[New Thread 0x7efd84779640 (LWP 31771)]
[New Thread 0x7efd8457a640 (LWP 31772)]
[New Thread 0x7efd8437b640 (LWP 31773)]
[New Thread 0x7efd837ff640 (LWP 31774)]
[New Thread 0x7efd837be640 (LWP 31775)]
[New Thread 0x7efd8374a640 (LWP 31776)]
[New Thread 0x7efd83709640 (LWP 31777)]
Thread 1 "Web Content" received signal SIGSEGV, Segmentation fault.
0x000055e6a900d603 in mozalloc_abort ()
(gdb) bt
#0  0x000055e6a900d603 in mozalloc_abort ()
#1  0x000055e6a900d6db in  ()
#2  0x000055e6a900d657 in  ()
#3  0x000055e6a900fafc in void std::vector<unsigned char, std::allocator<unsigned char> >::_M_range_insert<unsigned char const*>(__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, unsigned char const*, unsigned char const*, std::forward_iterator_tag) ()
#4  0x00007efd9e0380a2 in DoIntercept(unsigned int, recordreplay::CallArguments*) (aFunctionId=453, aArguments=0x7ffd2f4975c0)
    at src/cpp/recording/RecordedCall.cpp:280
#5  0x00007efd8b8944a1 in  ()
#6  0x00007efd8bafb000 in  ()
#7  0x00000000000006b1 in  ()
#8  0x00000000000001cf in  ()
#9  0x0000000000000000 in  ()
```

Here is the output from the replay proces itself:

```
updateRecordingDriver: fetch() not in scope, waiting...
updateRecordingDriver: fetch() not in scope, waiting...
updateRecordingDriver: fetch() not in scope, waiting...
updateRecordingDriver: fetch() not in scope, waiting...
updateRecordingDriver Starting... [Driver /home/marvin/.recordreplayinc/replay/linux-recordreplay.so]
CloudReplayStatus 
updateRecordingDriver AlreadyOnLatestVersion
Attach 31536 linux-gecko-20201205153659
Busy-waiting... (pid 31536) (tid 0)
[#0/1 129.725] SendMessage 1 Internal.createRecording
[#0/1 129.731] AttachBinary /home/marvin/Misc/install/replay/libxul.so
Mapped /home/marvin/Misc/install/replay/libxul.so: 0x7efd9e144000 [195798404 bytes]
[#0/1 129.838] AttachBinary /home/marvin/Misc/install/replay/replay
Mapped /home/marvin/Misc/install/replay/replay: 0x55e6a8fe7000 [741912 bytes]
[#0/1 129.838] AttachBinary /home/marvin/Misc/install/replay/libnspr4.so
Mapped /home/marvin/Misc/install/replay/libnspr4.so: 0x7efdabb0a000 [255656 bytes]
[#0/1 129.839] AttachBinary /home/marvin/Misc/install/replay/libplc4.so
Mapped /home/marvin/Misc/install/replay/libplc4.so: 0x7efdac0b0000 [20777 bytes]
[#0/1 129.839] AttachBinary /home/marvin/Misc/install/replay/libplds4.so
Mapped /home/marvin/Misc/install/replay/libplds4.so: 0x7efdac0ab000 [16577 bytes]
[#0/1 129.839] AttachBinary /home/marvin/Misc/install/replay/liblgpllibs.so
Mapped /home/marvin/Misc/install/replay/liblgpllibs.so: 0x7efdac09e000 [49280 bytes]
[#0/1 129.839] AttachBinary /home/marvin/Misc/install/replay/libnssutil3.so
Mapped /home/marvin/Misc/install/replay/libnssutil3.so: 0x7efdab8ce000 [203152 bytes]
[#0/1 129.839] AttachBinary /home/marvin/Misc/install/replay/libnss3.so
Mapped /home/marvin/Misc/install/replay/libnss3.so: 0x7efdab825000 [689844 bytes]
[#0/1 129.840] AttachBinary /home/marvin/Misc/install/replay/libsmime3.so
Mapped /home/marvin/Misc/install/replay/libsmime3.so: 0x7efdab7f8000 [182612 bytes]
[#0/1 129.840] AttachBinary /home/marvin/Misc/install/replay/libmozsqlite3.so
Mapped /home/marvin/Misc/install/replay/libmozsqlite3.so: 0x7efdab6b6000 [1317304 bytes]
[#0/1 129.840] AttachBinary /home/marvin/Misc/install/replay/libssl3.so
Mapped /home/marvin/Misc/install/replay/libssl3.so: 0x7efdab64e000 [423634 bytes]
[#0/1 129.840] AttachBinary /home/marvin/Misc/install/replay/libmozgtk.so
Mapped /home/marvin/Misc/install/replay/libmozgtk.so: 0x7efdac09b000 [8217 bytes]
[#0/1 129.929] Warning: disallowing dlopen() on unknown library libJitPI.so
out of memory: 0x00007FFD2F4979D4 bytes requested
CloudReplayStatus cloudError.label
CloudReplayStatus cloudReconnecting.label
```

**Comment by bhackett1024** [comment]
Moved to https://github.com/RecordReplay/backend/issues/543
