### ISSUE TITLE
Replay browser fails to launch for playwright tests 50% of the time

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/gecko-dev#342]
Launching the playwrights tests on my Mac results fails to launch the replay browser successfully 50% of the time. Launching firefox without replay works every time.

```
❯ PLAYWRIGHT_BROWSERS_PATH=$PWD/browsers RECORD_REPLAY_DRIVER=$PWD/browsers/firefox-1225/macOS-recordreplay.so RECORD_REPLAY_RECORDING_ID_FILE=$PWD/recordings.log RECORD_REPLAY_SERVER=wss://dispatch.replay.io RECORD_ALL_CONTENT=1 DEBUG=pw:browser*,pw:api node examples/reactcharts.js
  pw:api => browserType.launch started +0ms
  pw:browser <launching> /Users/RyanDuffy/dev/playwright-tests/browsers/firefox-1225/firefox/Nightly.app/Contents/MacOS/firefox -no-remote -wait-for-browser -foreground -profile /var/folders/bh/b3624d5s2sdb90b0p6zwjrm00000gp/T/playwright_firefoxdev_profile-hpRbAV -juggler-pipe -silent +0ms
  pw:browser <launched> pid=72420 +2ms
  pw:browser <gracefully close start> +30s
  pw:browser <kill> +1ms
  pw:browser <process did exit: exitCode=null, signal=SIGKILL> +22s
  pw:browser <gracefully close end> +1ms
  pw:api <= browserType.launch failed +52s
Error in React-charts
browserType.launch: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> /Users/RyanDuffy/dev/playwright-tests/browsers/firefox-1225/firefox/Nightly.app/Contents/MacOS/firefox -no-remote -wait-for-browser -foreground -profile /var/folders/bh/b3624d5s2sdb90b0p6zwjrm00000gp/T/playwright_firefoxdev_profile-hpRbAV -juggler-pipe -silent
<launched> pid=72420
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (/Users/RyanDuffy/dev/playwright-tests/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/Users/RyanDuffy/dev/playwright-tests/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /Users/RyanDuffy/dev/playwright-tests/node_modules/playwright/lib/client/browserType.js:61:73
    at BrowserType._wrapApiCall (/Users/RyanDuffy/dev/playwright-tests/node_modules/playwright/lib/client/channelOwner.js:72:34)
    at BrowserType.launch (/Users/RyanDuffy/dev/playwright-tests/node_modules/playwright/lib/client/browserType.js:52:21)
    at /Users/RyanDuffy/dev/playwright-tests/src/helpers.js:54:49
    at /Users/RyanDuffy/dev/playwright-tests/src/helpers.js:22:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'TimeoutError'
}
```

**Comment by ryanjduffy** [comment]
`PLAYWRIGHT_BROWSERS_PATH=$PWD/browsers node examples/tablecheck.js` also repros the behavior

**Comment by bhackett1024** [comment]
Hmm, I just tried this a few times and it always worked for me.  Are you still running into this?  On my computer I get a `*** You are running in headless mode.` message printed next, which I'm pretty sure originates from the parent process before we try to do anything record/replay related and suggests a problem with the browser install or initial browser launch.  A couple things to try:

1. Do you get the same behavior if you use the same PLAYWRIGHT_BROWSERS_PATH env var but not the other record/replay ones?

2. We have a run.ts script that manages the environment variables and the special browser directory, do you get the same behavior with that?

**Comment by ryanjduffy** [comment]
I still have the issue when running the above command but not when using `run.ts`. Not sure what the difference is but I don't think any more work is required for this.
